# Generated by Django 5.2.8 on 2025-11-18 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['-usage_count', 'name']},
        ),
    ]
