# Generated by Django 5.2.8 on 2025-11-17 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=200, unique=True)),
                ('is_live', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='builder.portfolio')),
            ],
        ),
    ]
