# Generated by Django 5.2.8 on 2025-11-21 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
        ('themes', '0004_userprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedsite',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.userprofile'),
        ),
    ]
