# Generated by Django 5.2.8 on 2025-11-21 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_initial'),
        ('publish', '0002_alter_publishedsite_portfolio'),
        ('themes', '0004_userprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.userprofile'),
        ),
        migrations.AlterField(
            model_name='education',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.userprofile'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.userprofile'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.userprofile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.userprofile'),
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
