# Generated by Django 5.2.8 on 2025-11-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_alter_skill_portfolio_alter_education_portfolio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='text_color',
        ),
    ]
